# Generated by Django 4.2.4 on 2024-11-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.AlterModelTable(
            name='booking',
            table='bookings',
        ),
    ]
